# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_image": "02_image.ipynb",
         "show_image": "02_image.ipynb",
         "show_images": "02_image.ipynb"}

modules = ["image.py"]

doc_url = "https://fastwandb.github.io/fastwandb/"

git_url = "https://github.com/fastwandb/fastwandb/tree/master/"

def custom_doc_links(name): return None
